spring.application.name=skillswap-backend
spring.profiles.active=dev

# H2 Database Dev Configuration (In-Memory for easy initial development)
spring.datasource.url=jdbc:h2:mem:skillswapdb;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
